name: test

on:
  push: 
    branches:
      - main
      - dev

jobs:
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name : test wf
      - run : echo "hello"
