name: test

on:
  push: 
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
    test:
      runs-on: ubuntu-latest 
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        - name : test wf
          run : echo "hello"
